version: '3.3'

services:


  #1. nginx

  nginx:
    image: "nginx"                  #1) nginx 이미지 가져오기
    ports:                          #2) 밖과 5000, 안과 80 포트로 연결
      - "5000:80"
    container_name: recipe_nginx    #3) 컨테이너 이름 redipe_nginx로 설정


  #2. 마리아DB 데이터베이스
  
  mariadb:                           
    image: mariadb:latest            #1) 도커 허브에서 latest 마리아DB 순정 이미지를 다운받기
    container_name: recipe_mariadb   #2) 컨테이너 이름 redipe_mariadb로 설정
    restart: always                  #3) 컴퓨터가 예기치 못하게 꺼지면 자동으로 다시 켜기
    environment:                     #4) 마리아DB 내 기본 환경 설정 (패스워드, 데이터베이스)
      MARIADB_ROOT_PASSWORD: '1234'
      MARIADB_DATABASE: 'recipe_db' 
      #MARIADB_USER: user
      #MARIADB_PASSWORD: password
    ports:
      - "3307:3306"                    #5) 밖과 3306 포트로 안과 3307 포트로 연결 (호스트 포트 : 도커 내부 포트)
    volumes:
      - mariadb_data:/var/lib/mysql    #6) 컨테이너와 /var/lib/mysql 연결 (호스트 경로:컨테이너 경로)



  #3. 파이썬 플라스크 웹 서버

  web:                               
    build: .                         #1) 현재 폴더에 있는 'Dockerfile'을 읽어오기
    container_name: recipe_flask     #2) 컨테이너 이름 recipe_flask로 설정
    restart: always                  #3) 문제가 생겨서 꺼지면 자동으로 다시 켜라
    ports:
      - "5001:5000"                  #4) 인터넷 주소창으로 5000 포트로 접속시 플라스크와 연결
    environment:
      - FLASK_ENV=development        #5) 플라스크를 '개발 모드'로 켠다 (에러 메시지를 자세히 보여줌)
    depends_on:
      - mariadb                      #6) 마리아DB가 켜지면 플라스크 실행
    volumes:                         #7) 플라스크와 /app/recipe_data6.csv 연결 (호스트 경로:컨테이너 경로)
      - ./recipe_data6.csv:/app/recipe_data6.csv


#4. 저장공간 설정

volumes:
  mariadb_data:                      #컨테이너를 삭제해도 데이터베이스 내용이 날아가지 않도록 저장공간 생성
